// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMPeKBqZB59thBERqyOj3jmaRULP67RAE',
    appId: '1:535746269323:android:6b9a4bb8a6e0b331b7848e',
    messagingSenderId: '535746269323',
    projectId: 'to-do-46ccf',
    databaseURL: 'https://to-do-46ccf-default-rtdb.firebaseio.com',
    storageBucket: 'to-do-46ccf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUofHj_NiEADCaC1_t1YJ4YQz3YCNTedQ',
    appId: '1:535746269323:ios:16ec2c77078a7011b7848e',
    messagingSenderId: '535746269323',
    projectId: 'to-do-46ccf',
    databaseURL: 'https://to-do-46ccf-default-rtdb.firebaseio.com',
    storageBucket: 'to-do-46ccf.appspot.com',
    iosClientId: '535746269323-i2dhb5n7h62tpi4uglsemkiepdko0gak.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoApp',
  );
}
